name: LSM CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_IMAGE_NAME: lsm
jobs:
  test:
    name: Build and Test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-ci
          push: false
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Test Image
        run: docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:latest make coverage

